name: quotescript_ui
description: QuoteScript Desktop UI
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider:
  path:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  icons_launcher:

# icons_launcher configuration (THIS is what the tool expects)
icons_launcher:
  image_path: "assets/quotescript_logo.png"
  platforms:
    windows:
      enable: true
    macos:
      enable: true
    linux:
      enable: true

flutter:
  uses-material-design: true
  assets:
    - assets/quotescript_logo.png
